services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal

  api:
    image: llm-metadata-harvester-service-api:prod
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - internal

  worker:
    image: llm-metadata-harvester-service-worker:prod
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - internal

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      # future TLS
      # - "443:443"
    volumes:
      - ./nginx/nginx.public.conf:/etc/nginx/nginx.conf:ro
     # - ./certs:/etc/nginx/certs:ro            <-- certificates must be placed and loaded 
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - internal
      - public

networks:
  internal:
    internal: true
  public:
