version: "3.9"

services:
  api:
    build: .
    container_name: llm-metadata-harvester-service-api
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: llm-metadata-harvester-service-worker
    command: celery -A llm_metadata_harvester_service.core.celery_app.celery_app worker -l info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: llm-harvester-redis
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: llm-harvester-nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
